function createfigure(xvector1, yvector1)
%CREATEFIGURE(xvector1, yvector1)
%  XVECTOR1:  bar xvector
%  YVECTOR1:  bar yvector

%  Auto-generated by MATLAB on 29-Jul-2020 08:01:52

% Create figure
figure1 = figure;

% Create axes
axes1 = axes('Parent',figure1);
hold(axes1,'on');

% Create bar
bar1 = bar(xvector1,yvector1,'Clipping','off','LineWidth',1,...
    'FaceColor',[0.741176470588235 0.333333333333333 0],...
    'BarWidth',1);

% The following line demonstrates an alternative way to create a data tip.
% datatip(bar1,4.5,4);
% Create datatip
datatip(bar1,'DataIndex',5);

% Create ylabel
ylabel('Poèet novorozencù','FontWeight','bold');

% Create xlabel
xlabel('Èas (h)','FontWeight','bold');

% Uncomment the following line to preserve the X-limits of the axes
 xlim(axes1,[0 24]);
% Uncomment the following line to preserve the Y-limits of the axes
 ylim(axes1,[0 4.3]);
% Set the remaining axes properties
set(axes1,'FontSize',12,'FontWeight','bold','LineWidth',1.3,'TickDir','out',...
    'XTick',[0 3 6 9 12 15 18 21 24],'YTick',[1 2 3 4]);
